name: Hourly Update Predictions

on:
  schedule:
    - cron: '0 * * * *'    # каждый час
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Установить Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установить зависимости
      run: |
        pip install requests pandas scikit-learn optuna

    - name: Обновить прогнозы
      run: python scripts/update_predictions.py

    - name: Пуш изменений в gh-pages
      run: |
        git config user.name 'github-actions'
        git config user.email 'actions@github.com'
        git add hockey_predictions.csv tennis_predictions.csv
        git commit -m 'Hourly update'
        git push origin gh-pages --force
